version: "3.8"
services:
  emacs:
    image: spacemacs2go
    ports:
      - "2222:22"
    environment:
      - http_proxy=...
      - HTTP_PROXY=...
      - https_proxy=...
      - HTTPS_PROXY=...
      - no_proxy=...
      - NO_PROXY=...
    volumes:
      - type: volume
        source: ...
        target: /root/shared
      - type: bind
        source: ...
        target: /root/.spacemacs