
services:
  emacs2go:
    image: emacs2go
    ports:
      - "2222:22"
    environment:
      - http_proxy=...
      - HTTP_PROXY=...
      - https_proxy=...
      - HTTPS_PROXY=...
      - no_proxy=...
      - NO_PROXY=...
    volumes:
      - type: volume
        source: ...
        target: ~/shared
      - type: bind
        source: ...
        target: ~/.spacemacs